### ISSUE TITLE
"Indent is negative" warnings that seem to break indentation.

### ISSUE THREAD

**Issue by DeathOfBalance** [WGUNDERWOOD/tex-fmt#40]
I'm not sure what's going on, but for some of my .tex files, at some point I'll get lots of "indent is negative" warnings, and from that point on the indentation will not work as intended. Here is a working example:

```
\documentclass[11pt]{article}
%\usepackage{francais}
\usepackage{amssymb, latexsym, amsmath}
\usepackage[french]{babel}
\usepackage[utf8]{inputenc}
\usepackage{tikz}
\usepackage{nicefrac}
\usepackage[T1]{fontenc}
\usepackage{siunitx}

\usepackage[french=guillemets]{csquotes}
%\MakeAutoQuote{»}{«}
\MakeOuterQuote{"}

\usetikzlibrary{calc,through,backgrounds,positioning,shadows,fadings,arrows}
\tikzstyle{fancytitle} =[draw=black, very thick, fill=white,
rectangle, rounded corners]
\tikzset{wdisk/.style={circle,color=black, fill=white, inner sep =0.5pt, minimum size =1pt}}

\usepackage{tasks}
\usepackage{siunitx}
\sisetup{
  group-separator = {\,},      % Use thin space for grouping digits
  group-minimum-digits = 3,    % Group every 3 digits
  output-decimal-marker = {,}  % Use comma as the decimal marker
}
\usepackage{wrapfig}
\usepackage[top=1cm,left=1.9cm,right=1.9cm,bottom=2cm]{geometry}
\usepackage{enumitem}
\usepackage{multicol}
\usepackage{lmodern}
\renewcommand{\labelenumi}{\alph{enumi})}
\renewcommand{\theenumi}{\alph{enumi})}

\usepackage[bottom]{footmisc}
\renewcommand{\thefootnote}{\fnsymbol{footnote}}
\newcommand{\spaces}{\vspace{0.6cm}}
\newcommand{\spacem}{\vspace{6cm}}
\newcommand{\spacel}{\vspace{10cm}}

\newlist{problemes}{enumerate}{1}
\setlist[problemes]{label=\textbf{Problème \arabic*}, align=left}

\newcommand{\li}[1]{ \lim_{x \to #1}}
\everymath{\displaystyle}

\begin{document}

\noindent \textbf{Nom} : \fbox{\phantom{\huge Sernom serl fds fds ff asdf    aaaaa  ong ça s'}} \hfill /80+\textbf{6} points
%\makeemptybox{3em}

\begin{center}
\section*{Examen 2 (20\%)}
\end{center}
\begin{enumerate}
	\item flkjfds

		fjsg


	\item gjf
\end{enumerate}
```

Everything works fine up to \renewcommand, but then it breaks down.

**Comment by WGUNDERWOOD** [comment]
This is because you have an unmatched parentheses in 
```
\renewcommand{\labelenumi}{\alph{enumi})}
\renewcommand{\theenumi}{\alph{enumi})}
```
I recommend ignoring these lines by appending `% tex-fmt: skip` to the end: try instead
```
\renewcommand{\labelenumi}{\alph{enumi})} % tex-fmt: skip
\renewcommand{\theenumi}{\alph{enumi})} % tex-fmt: skip
```
This fixes the issue for me.

**Comment by viktorashi** [comment]
But, @WGUNDERWOOD  what if my file actually just uses `)` closed parantheses as part of my notation ,for example some conditions in a theorem like
i)
ii)
iii)

or the naming of sub-exercises?

a)
b)
c) ...
etc. , do I need to regex every single line that has an unmatched ")" and append `% tex-fmt: skip` to it? 


Aahh I'll learn Rust someday and contribute to this project because it's really got so much to it, and it's just such a shame that `latexindent` does what I want in this context exact it just takes annoyingly long compared to your masterpiece

**Comment by WGUNDERWOOD** [comment]
I agree with your concern, @viktorashi; I think the long-term solution will be to avoid indenting based on delimiters outside of math environments. However, in your specific case, I think the "best" solution is to define and use an environment which programatically creates the i), ii) etc using `\item` rather than writing them by hand. For example, I often use:

```latex
\newlist{inlineroman}{enumerate*}{1}
\setlist[inlineroman]{afterlabel=~,label=(\roman*)}

\begin{inlineroman}
  \item Proving the first part.
  \item Proving the second part.
\end{inlineroman}

\begin{document}
\end{document}
```

**Comment by viktorashi** [comment]
You're an actual genius, not only did that fix my problem, but I was using it in LaTeX Workshop in VsCode and I also used your suggestion from https://github.com/WGUNDERWOOD/tex-fmt/issues/91#issuecomment-2850589550 to pass `--quiet` to it and now it works if i run `tex-fmt` myself manually AND when saving in vscode 

It's true that I should (if it wasn't already) file an issue for LaTeX Workshop themselves forthe way it handles the error lines or something, because otherwise, everything just freezes.

Thanks again and have a great day!
